### ISSUE TITLE
Semicolon added on paste

### ISSUE THREAD

**Issue by AndreJesusBrito** [denoland/vscode_deno#102]
I have been working with the deno extension for a few days and I'm very happy with it.
However there is something kind of annoying happening.
When I copy and paste some text anywhere, regardless of the context, a semicolon is added to the end.

This is very inconvenient when copying names of variables or copying values to arrays, parameters and objects

For example, lets suppose that we want to copy the values of `a` to `b`
```ts
var a = [1,2,3];
var b = []
```
The result after the copy is:
```ts
var b = [1, 2, 3;]
```

I disabled all other extensions except deno and this still happening.
If deno extension is disabled the semicolon its not added.

I'm not sure if this is a bug but I made some observations:
- only happens if the file is saved in disk
- is not added for some keywords, parenthesis and brackets when pasted
- is added even after the `Deno: Disable Deno` command
- doesn't happen when the paste is more than one line (if not indented)

Thank you very much.
If some extra info is required please tell me, I will reply as soon as I can.

**Comment by lucacasonato** [comment]
What formatter are you using in VS Code? The `Deno` formatter from the Deno extension?

**Comment by AndreJesusBrito** [comment]
@lucacasonato I'm not really sure to be honest.
I never changed the formatting settings.

For now I have only `Deno` extension enabled:
![image](https://user-images.githubusercontent.com/35274086/86840633-dc324500-c09a-11ea-9ec0-a60d18d7eff4.png)
As soon I disable `Deno` extension and reload VS Code it stops adding the semicolon.
As soon as I enable the extension it adds semicolons on paste again.

So it should be `Deno` formatter

Also:
![image](https://user-images.githubusercontent.com/35274086/86842390-05ec6b80-c09d-11ea-9faf-f1b32f1deb3b.png)
Here when I choose `null` or `denoland.vscode-deno` it adds the semicolon.
Other formats don't seem to do it (didn't test for all, but `vscode.typescript-language-features` and `vscode.npm` don't do it ).

These are the settings that I have when I search for "semicolon" on the VS Code settings
![image](https://user-images.githubusercontent.com/35274086/86847611-7f3b8c80-c0a4-11ea-8f15-a75b759509e4.png)

And this my VS Code about info:
```
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```

Hope this helps, cheers.

**Comment by lucacasonato** [comment]
This should be fixed now because we do not auto format on save now.

**Comment by jameshartig** [comment]
I'm still having this issue. Deno plugin is 2.3.3 and VSCode is 1.52.1.

https://user-images.githubusercontent.com/112555/103785646-743cc700-5009-11eb-859f-a4fc36f9a5f4.mp4

**Comment by lgarron** [comment]
> I'm still having this issue. Deno plugin is 2.3.3 and VSCode is 1.52.1.

I'm also encountering this. Every single paste is appended with an extra semicolon, which also makes the formatter freak out and pop up an error message every time.

<img width="969" alt="Screen Shot 2021-01-31 at 17 19 35" src="https://user-images.githubusercontent.com/248078/106404756-9814e200-63e8-11eb-8553-d71e2aa7f5cc.png">

(My instinct is to press the "X" to make the message go away, which takes me to the `OUTPUT` panel. I always have to click back to `TERMINAL` manually.)

macOS 10.15.7
VSCode Version: 1.52.1
Deno extension version 2.3.3

> deno --version
deno 1.7.1 (release, x86_64-apple-darwin)
v8 8.9.255.3
typescript 4.1.3

**Comment by JeromeGill** [comment]
Turn off the "format on paste" option
<img width="926" alt="Screenshot 2022-01-06 at 19 50 46" src="https://user-images.githubusercontent.com/2402476/148468546-684e2d76-0b51-4657-b334-c6128060f57f.png">

**Comment by Sean0717** [comment]
> Turn off the "format on paste" option <img alt="Screenshot 2022-01-06 at 19 50 46" width="926" src="https://user-images.githubusercontent.com/2402476/148468546-684e2d76-0b51-4657-b334-c6128060f57f.png">

it resolves my problem
