### ISSUE TITLE
LSP crashed in non deno project

### ISSUE THREAD

**Issue by shevernitskiy** [denoland/vscode_deno#1041]
**Describe the bug**

I have nestjs project for node. In this project I have simple const object like 
```ts 
const AMO = {
  CUSTOM_FIELD: {
    /* ---------------------------------- Заказ --------------------------------- */
    ORDER_ID: 1366662, // Номер заказа
    PREPAY: 1376228, // Предоплата
    FULLPAY: 1997465, // Полная оплата
    PAY_TYPE: 1376058, // Тип оплаты
    DISCOUNT: 1376070, // Скидка
    DELIVERY_TIME: 1376026, // Время доставки
    COMMENT_CLIENT: 1340240, // Комментарий клиента
    COMMENT_MANAGER: 1376098, // Комментарий менеджера
    /* -------------------------------- Доставка -------------------------------- */
    DELIVERY_TYPE: 1337998, // Тип доставки
    DELIVERY_COST: 1334194, // Стоимость доставки
    INDEX: 1454436, // Адрес, индекс
    CITY: 1369856, // Адрес, города
    STREET: 1369858, // Адрес, улица
    HOUSE: 1454432, // Адрес, дом
    FLAT: 1454434, // Адрес, квартира
    TRACK_NUMBER: 1430854, // Трек-код
    /* ---------------------------------- СДЭК ---------------------------------- */
    CDEK_CITY_ID: 1413328, // СДЭК, город id
    CDEK_DELIVERY_DATE: 1413332, // СДЭК, дата отправки
    CDEK_UUID: 1997423, // СДЭК, uuid
    CDEK_INVOICE_URL: 1997427, // СДЭК, накладная
    CDEK_STATUS: 1997433, // СДЭК, последний статус
    CDEK_PREIOD: 1997435, // СДЭК, сроки доставки
    CDEK_COMMENT: 1997537, // СДЭК, комментарий для курьера
  },
  /* ------------------------------ Поля контакта ----------------------------- */
  CONTACT: {
    PHONE: 1305898, // Контакт, телефон
    EMAIL: 1305900, // Контакт, почта
  },
  /* ----------------------------- Статусы воронки ---------------------------- */
  STATUS: {
    CLAIM: 12470886, // Заявка
    REQUISITE: 12601569, // Реквизиты
    PAYMENT: 12528897, // Отплаты
    DELIVERY: 12470889, // Доставка
    POST: 12470892, // Почта
    CDEK: 12470895, // СДЭК
    VISIT: 12523860, // Визиты
    SENT: 12601911, // Отправлено
    SUCCESS: 142, // Успешно реализовано
    CLOSED: 143, // Закрыто и не реализовано
    RETURN: 30999157, // Возвраты
  },
  /* ---------------------------------- Тэги ---------------------------------- */
  TAG: {
    SITE: 92650, // с стайта
    CALL_REQUEST: 683220, // Заказ зввонка
    RETURN: 683287, // возврат
    INVOICE: 683303, // накладная
    TRACK: 683505, // трэк-код
  },
  /* ------------------------------ Пользователи ------------------------------ */
  USER: {
    ADMIN: 1092156, // Меховой салон GERDA
    EKATERINA: 1109421, // Екатерина
    OLGA: 1110687, // Ольга
  },
  /* -------------------------------- Каталоги -------------------------------- */
  CATALOG: {
    GOODS: 3272, // Список товаров
  },
  /* --------------------------------- Воронки -------------------------------- */
  PIPELINE: {
    MAIN: 311787, // Основная воронка
    RETURN: 2217028, // Возвраты
  },
  /* --------------------------------- Задачи --------------------------------- */
  TASK: {
    CALL: 1, // Связаться с клиентом
    PROCESS: 1746622, // Обработать
    ERROR: 1743178, // Ошибка
    EMAIL: 1604317, // Написать письмо
    RECALL: 1363711, // Повторный звонок
  },
} as const;
 ```

Deno LSP crashed here, but with disabled deno extension all works fine, intellisense works.

Deno LSP debug output:
```sh
Starting Deno language server...
  version: 1.40.0 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\mahah\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.85.2
{"type":"mark","name":"lsp.update_cache"},
{"type":"measure","name":"lsp.update_cache","count":1,"duration":0.009},
  Auto-resolved package.json: "file:///E:/programming/ts/gerda/package.json"
{"type":"mark","name":"lsp.update_tsconfig"},
{"type":"mark","name":"tsc.request.$configure"},
{"type":"mark","name":"tsc.host.$configure","count":1,"args":[{"allowJs":true,"esModuleInterop":true,"experimentalDecorators":true,"isolatedModules":true,"jsx":"react","lib":["deno.ns","deno.window","deno.unstable"],"module":"esnext","moduleDetection":"force","noEmit":true,"resolveJsonModule":true,"strict":true,"target":"esnext","useDefineForClassFields":true,"useUnknownInCatchVariables":false}]},
{"type":"measure","name":"tsc.host.$configure","count":1,"duration":1.168},
{"type":"measure","name":"tsc.request.$configure","count":1,"duration":122.339},
{"type":"measure","name":"lsp.update_tsconfig","count":1,"duration":122.419},
{"type":"mark","name":"tsc.request.$getSupportedCodeFixes"},
{"type":"mark","name":"tsc.host.$getSupportedCodeFixes","count":1,"args":[]},
{"type":"measure","name":"tsc.host.$getSupportedCodeFixes","count":1,"duration":0.589},
{"type":"measure","name":"tsc.request.$getSupportedCodeFixes","count":1,"duration":0.733},
{"type":"mark","name":"lsp.update_import_map"},
{"type":"measure","name":"lsp.update_import_map","count":1,"duration":0.002},
{"type":"mark","name":"lsp.update_registries"},
Enabling import suggestions for: https://deno.land
{"type":"measure","name":"lsp.update_registries","count":1,"duration":4.39},
{"type":"mark","name":"tsc.request.$getAssets"},
{"type":"mark","name":"tsc.host.$getAssets","count":1,"args":[]},
{"type":"measure","name":"tsc.host.$getAssets","count":1,"duration":1.434},
{"type":"measure","name":"tsc.request.$getAssets","count":1,"duration":1.754},
{"type":"measure","name":"lsp.initialize","count":1,"duration":138.72},
{"type":"mark","name":"lsp.did_open","count":1,"args":{"textDocument":{"uri":"file:///e%3A/programming/ts/gerda/src/amo/amo.constants.ts","languageId":"typescript","version":14,"text":"const AMO = {\r\n  CUSTOM_FIELD: {\r\n    /* ---------------------------------- Заказ --------------------------------- */\r\n    ORDER_ID: 1366662, // Номер заказа\r\n    PREPAY: 1376228, // Предоплата\r\n    FULLPAY: 1997465, // Полная оплата\r\n    PAY_TYPE: 1376058, // Тип оплаты\r\n    DISCOUNT: 1376070, // Скидка\r\n    DELIVERY_TIME: 1376026, // Время доставки\r\n    COMMENT_CLIENT: 1340240, // Комментарий клиента\r\n    COMMENT_MANAGER: 1376098, // Комментарий менеджера\r\n    /* -------------------------------- Доставка -------------------------------- */\r\n    DELIVERY_TYPE: 1337998, // Тип доставки\r\n    DELIVERY_COST: 1334194, // Стоимость доставки\r\n    INDEX: 1454436, // Адрес, индекс\r\n    CITY: 1369856, // Адрес, города\r\n    STREET: 1369858, // Адрес, улица\r\n    HOUSE: 1454432, // Адрес, дом\r\n    FLAT: 1454434, // Адрес, квартира\r\n    TRACK_NUMBER: 1430854, // Трек-код\r\n    /* ---------------------------------- СДЭК ---------------------------------- */\r\n    CDEK_CITY_ID: 1413328, // СДЭК, город id\r\n    CDEK_DELIVERY_DATE: 1413332, // СДЭК, дата отправки\r\n    CDEK_UUID: 1997423, // СДЭК, uuid\r\n    CDEK_INVOICE_URL: 1997427, // СДЭК, накладная\r\n    CDEK_STATUS: 1997433, // СДЭК, последний статус\r\n    CDEK_PREIOD: 1997435, // СДЭК, сроки доставки\r\n    CDEK_COMMENT: 1997537, // СДЭК, комментарий для курьера\r\n  },\r\n  /* ------------------------------ Поля контакта ----------------------------- */\r\n  CONTACT: {\r\n    PHONE: 1305898, // Контакт, телефон\r\n    EMAIL: 1305900, // Контакт, почта\r\n  },\r\n  /* ----------------------------- Статусы воронки ---------------------------- */\r\n  STATUS: {\r\n    CLAIM: 12470886, // Заявка\r\n    REQUISITE: 12601569, // Реквизиты\r\n    PAYMENT: 12528897, // Отплаты\r\n    DELIVERY: 12470889, // Доставка\r\n    POST: 12470892, // Почта\r\n    CDEK: 12470895, // СДЭК\r\n    VISIT: 12523860, // Визиты\r\n    SENT: 12601911, // Отправлено\r\n    SUCCESS: 142, // Успешно реализовано\r\n    CLOSED: 143, // Закрыто и не реализовано\r\n    RETURN: 30999157, // Возвраты\r\n  },\r\n  /* ---------------------------------- Тэги ---------------------------------- */\r\n  TAG: {\r\n    SITE: 92650, // с стайта\r\n    CALL_REQUEST: 683220, // Заказ зввонка\r\n    RETURN: 683287, // возврат\r\n    INVOICE: 683303, // накладная\r\n    TRACK: 683505, // трэк-код\r\n  },\r\n  /* ------------------------------ Пользователи ------------------------------ */\r\n  USER: {\r\n    ADMIN: 1092156, // Меховой салон GERDA\r\n    EKATERINA: 1109421, // Екатерина\r\n    OLGA: 1110687, // Ольга\r\n  },\r\n  /* -------------------------------- Каталоги -------------------------------- */\r\n  CATALOG: {\r\n    GOODS: 3272, // Список товаров\r\n  },\r\n  /* --------------------------------- Воронки -------------------------------- */\r\n  PIPELINE: {\r\n    MAIN: 311787, // Основная воронка\r\n    RETURN: 2217028, // Возвраты\r\n  },\r\n  /* --------------------------------- Задачи --------------------------------- */\r\n  TASK: {\r\n    CALL: 1, // Связаться с клиентом\r\n    PROCESS: 1746622, // Обработать\r\n    ERROR: 1743178, // Ошибка\r\n    EMAIL: 1604317, // Написать письмо\r\n    RECALL: 1363711, // Повторный звонок\r\n  },\r\n} as const;\r\n\r\n"}}},
{"type":"measure","name":"lsp.did_open","count":1,"duration":0.693},
{"type":"mark","name":"lsp.testing_update"},
{"type":"mark","name":"lsp.update_diagnostics_deps"},
{"type":"measure","name":"lsp.testing_update","count":1,"duration":0.037},
{"type":"mark","name":"lsp.update_diagnostics_lint"},
{"type":"mark","name":"lsp.did_open","count":2,"args":{"textDocument":{"uri":"file:///e%3A/programming/ts/gerda/src/amo/amo.controller.ts","languageId":"typescript","version":1,"text":"import { Body, Controller, Post, UseInterceptors } from \"@nestjs/common\";\r\nimport { LeadAddWebhook } from \"./webhooks/lead-add.webhook\";\r\nimport { AutoOkResponse } from \"../utils/auto-ok-response.interceptor\";\r\n\r\n@UseInterceptors(AutoOkResponse)\r\n@Controller(\"amo\")\r\nexport class AmoController {\r\n  constructor(private readonly lead_add: LeadAddWebhook) {}\r\n\r\n  // TODO: dto here to deserialization?\r\n  @Post(\"lead-add\")\r\n  async leadAdd(@Body() data: any): Promise<string> {\r\n    await this.lead_add.handle(data);\r\n    return \"OK\";\r\n  }\r\n}\r\n"}}},
{"type":"measure","name":"lsp.update_diagnostics_deps","count":1,"duration":0.367},
{"type":"measure","name":"lsp.update_diagnostics_lint","count":1,"duration":0.289},
{"type":"measure","name":"lsp.did_open","count":2,"duration":0.574},
{"type":"mark","name":"lsp.testing_update"},
{"type":"mark","name":"lsp.update_diagnostics_deps"},
{"type":"measure","name":"lsp.testing_update","count":2,"duration":0.024},
{"type":"mark","name":"lsp.update_diagnostics_lint"},
{"type":"measure","name":"lsp.update_diagnostics_deps","count":2,"duration":0.067},
{"type":"measure","name":"lsp.update_diagnostics_lint","count":2,"duration":0.064},
{"type":"mark","name":"lsp.update_tsconfig"},
{"type":"mark","name":"tsc.request.$configure"},
{"type":"mark","name":"tsc.host.$configure","count":2,"args":[{"allowJs":true,"esModuleInterop":true,"experimentalDecorators":true,"isolatedModules":true,"jsx":"react","lib":["deno.ns","deno.window","deno.unstable"],"module":"esnext","moduleDetection":"force","noEmit":true,"resolveJsonModule":true,"strict":true,"target":"esnext","useDefineForClassFields":true,"useUnknownInCatchVariables":false}]},
{"type":"measure","name":"tsc.host.$configure","count":2,"duration":0.326},
{"type":"measure","name":"tsc.request.$configure","count":2,"duration":0.47},
{"type":"measure","name":"lsp.update_tsconfig","count":2,"duration":0.541},
Could not set npm package requirements. Error getting response at https://registry.npmjs.org/@nestjs/common for package "@nestjs/common": An npm specifier not found in cache: "@nestjs/common", --cached-only is specified.
Server ready.
{"type":"mark","name":"lsp.update_diagnostics_deps"},
{"type":"mark","name":"lsp.update_diagnostics_lint"},
{"type":"measure","name":"lsp.update_diagnostics_deps","count":3,"duration":0.446},
{"type":"measure","name":"lsp.update_diagnostics_lint","count":3,"duration":0.456},
{"type":"mark","name":"lsp.update_diagnostics_ts"},
{"type":"measure","name":"lsp.update_diagnostics_ts","count":1,"duration":0.148},
```

**To Reproduce**

1. delcare the object
2. try to get intellisense when access the object

**Expected behavior**

Default VSCode TS can handle this. 

**Versions**

vscode: 1.85.2 deno: 1.40.0 (release, x86_64-pc-windows-msvc) extension: 3.33.0

**Just a question**

How can I disable Deno Extension for projects without `deno.json` by default?

**Comment by Mqxx** [comment]
Try downgrading to version `v3.31.0`. #1039

**Comment by shevernitskiy** [comment]
> Try downgrading to version `v3.31.0`. #1039

Thanks!

**Comment by nayeemrmn** [comment]
Fixed in 3.33.2

**Comment by shevernitskiy** [comment]
> Fixed in 3.33.2

It is not crashed now, but a still don't have intelisense for this object with enabled extension.

**Comment by nayeemrmn** [comment]
@shevernitskiy I can't reproduce that. You're expecting intellisense for node right? Can you share your workspace settings, and is there a `deno.json`/`deno.jsonc` in your project?

**Comment by shevernitskiy** [comment]
This is Node project without deno condig file, only `package.json`.  There are in no any additional vscode settings for workspace. I expect that deno extension do not work at all, but it somehow work for this project (and broke some things)

**Comment by nayeemrmn** [comment]
@shevernitskiy Can you check your global/user vscode settings?

**Comment by shevernitskiy** [comment]
<img width="1040" alt="image" src="https://github.com/denoland/vscode_deno/assets/28886342/d92262cd-0c6f-4f6b-8f61-c924f9f45b5d">

**Comment by nayeemrmn** [comment]
I'm not sure why that's happening with no enable settings or `deno.json` and I can't reproduce it. Can you open a new issue? We'll see if others are experiencing this. For now you can workspace-disable the Deno extension.

**Comment by nayeemrmn** [comment]
Also see if an explicit `"deno.enable": false` changes anything

**Comment by shevernitskiy** [comment]
> "deno.enable": false

it helps
