### ISSUE TITLE
npm import not recognizing all package contents

### ISSUE THREAD

**Issue by mBartoldus** [denoland/vscode_deno#1130]
When importing tensorflow from npm, vscode only recognizes the exports "tf.data" and "tf.version". All other exports, such as "tf.sequential" are not recognized.

**To Reproduce**

```ts
import * as tf from "npm:@tensorflow/tfjs"
console.log(tf.sequential)
```
if you run the above code, it will log `[Function: sequential]`. Therefore, the function exists, and deno has successfully imported it. But the vscode extension gives a "does not exist" error.

**Expected behavior**

All of the modules exports should be recognized and given appropriate intellisense.

**Screenshots**

<img width="457" alt="Screen Shot 2024-07-06 at 1 57 34 AM" src="https://github.com/denoland/vscode_deno/assets/79112778/8d3d28de-363a-4625-b323-50fa8d78c28b">
<img width="424" alt="Screen Shot 2024-07-06 at 4 09 07 PM" src="https://github.com/denoland/vscode_deno/assets/79112778/b50b0348-3676-4e14-ae91-cbd622cfc257">

**Versions**

vscode: 1.91.0 deno: 1.44.4 extension: 3.38.0

**Comment by nayeemrmn** [comment]
I've checked that this is fixed in canary, can you try again with `deno upgrade --canary`? Try restarting the window after updating just in case.

**Comment by mBartoldus** [comment]
The problem is not with deno, deno is working fine. The problem is with the vscode extension. I tried deno upgrade --canary, and it does not resolve my issue.
