### ISSUE TITLE
[Canary] DOM is not being included when declared as a lib in tsconfig

### ISSUE THREAD

**Issue by Arocide** [denoland/vscode_deno#318]
**Describe the bug**
deno-ts reports problems whenever dom types are used even when `dom` is declared as a lib in a tsconfig file.

Example of problem reported:
```Cannot find name 'document'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'.```

Including `ESNext`, `deno.window` or `es6` (and others) as libs seemingly work as intended so this seems to be specifically related to including `dom` within either the extension or the language service as using the same tsconfig with the `--config` flag for bundling works. 

**Used Configs**
vscode settings.json:
```javascript
{
  "deno.config": "./tsconfig.json",
  "deno.enable": true,
  "deno.lint": true,
}
```
tsconfig.json:
```javascript
{
    "compilerOptions": {
        "lib": [ "ESNext",  "dom", ],
    },
}
```

**Expected behavior**

Deno should not report problems for DOM types when included as a lib within a tsconfig file.

**Versions**
vscode: 1.54.0-insider (Also checked on 1.53.0)
deno: 1.7.2 (release, x86_64-pc-windows-msvc)
extension:  denoland.vscode-deno-canary 0.0.8

**Comment by esquevin** [comment]
Encountering the exact same issue. 

Currently the extension is telling me 
`Cannot find name 'console'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'.deno-ts(2584)`

Even though I got 
```{
  "compilerOptions": {
    "jsx": "react",
    "jsxFactory": "h",
    "lib": ["dom", "ESNext"],
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true
  }
}```

I'm sure that my tsconfig.json is properly loaded since when I disable the JSX configuration line, all my JSX is reported as error

**Comment by kitsonk** [comment]
I believe this is now fixed in 3.0.1 and Deno 1.7.5.

**Comment by newtack** [comment]
I had a similar problem and at first it looked like it was not fixed. I did put in a tsconfig.json into the root directory specifying DOM in the lib array, and it was still not working with the latest version.

I then specified the "deno.config" setting in the workspace settings to point to this tsconfig.json, reloaded and it now picks up DOM typing. So as kitsonk stated, it is is now fixed, but you have to specify not just tsconfig.json but also point to it in "deno.config".

**Comment by Buraburaite** [comment]
I just had this exact same problem today and resolved it with @newtack's solution.
Deno v1.10.2
vscode-deno v.3.4.0
VSCodium 1.56.2

[Deno is designed to be usable without a tsconfig.json by default](https://deno.land/manual@v1.10.2/typescript/configuration), so having to do this so that the deno-ts linter would recognize `console` and `Deno` was definitely frustrating. It the extension was providing an empty tsconfig file by default, overriding Deno's defaults 🤷🏻‍♂️

**Comment by kitsonk** [comment]
> Deno is designed to be usable without a tsconfig.json by default, so having to do this so that the deno-ts linter would recognize console and Deno was definitely frustrating.

It does work by default, without a `tsconfig.json` and your `tsconfig.json` seems quite "wrong".  I suspect you were encountering another issue.

**Comment by Buraburaite** [comment]
That seems logical. Whatever the cause, I wasn't able to figure it out yesterday, and it made most of yesterday completely unproductive until I found this solution. Hopefully this helps someone in the same situation, whatever the cause.

To be clear (and I just replicated this on my machine before writing this response) my issue is that I get `Cannot find name 'console'` and `Cannot find name 'Deno'` unless I have a `tsconfig.json` in my root with `deno.window` in `compilerOptions.lib`.

When I delete the `tsconfig.json` and then restart the language server with the command palette, the issue shows up again. When I remake that `tsconfig.json` and restart again, I instead get `var console: Console` and `namespace Deno`.

I have not set `deno.config` anywhere. Not in User or Workspace settings, and not in `.vscode/settings`. So, yeah. It's really weird. I don't know what's causing it.

**Comment by kitsonk** [comment]
@Buraburaite what is the output of `Deno Language Server` (you can view output under the `View | Output` menu) and what is in your `.vscode/setttings.json`?

**Comment by Buraburaite** [comment]
Okay, now that I know how to look at the output, I *think* I figured out what was happening.

When I reload the window and it's not working, I get this output:
```
Starting Deno language server...
  version: 1.10.2 (release, x86_64-apple-darwin)
Connected to "VSCodium" 1.56.2
Updating TypeScript configuration from: ""
Updating tsconfig has errored: Failed to load configuration file
language server initialized
Server ready.
```
This is even though I have not set config anywhere. _But_ if I hit "reset setting" on the config variable and reload the window (restarting the server alone seems inconsistent?), the problem goes away.

My theory is that at some point I wrote something in config, and then deleted it, but the extension still sees an empty string instead of null. Like, it's trying to load `${root}/${config}` when `config === ''` instead of ignoring the config variable.

In fact, when I go to config in settings, add a space, then delete it, this is the output:
```
Starting Deno language server...
  version: 1.10.2 (release, x86_64-apple-darwin)
Connected to "VSCodium" 1.56.2
language server initialized
Server ready.
Updating TypeScript configuration from: " "
Updating TypeScript configuration from: ""
```

Here is my `.vscode/settings.json`. I'm now able to toggle the issue on and off with just the empty string thing and reloading the window (I deleted the `tsconfig.json`).
```json
{
    "deno.enable": true, // enables extension
    "deno.lint": true,
    "deno.unstable": true
}
```

**Comment by YYX-KISS** [comment]
在使用deno的第三方库deno-create-react-app这个脚手架时，vscode提示了该错误，但事实上程序时可以正确的运行的，也许正如楼上@Buraburaite所说[Deno is designed to be usable without a tsconfig.json by default]。
我通过在settings.json中指定tsconfig文件的位置{"deno.config": "./tsconfig.json"},成果解决的vscode的报错。
<img width="335" alt="image" src="https://user-images.githubusercontent.com/98140092/187038255-92f7d240-04c1-4e24-a84d-1c138ac521a9.png">

**Comment by manen** [comment]
why is this closed this is still happening
