### ISSUE TITLE
Command 'Deno: Reload Import Registries Cache' resulted in an error

### ISSUE THREAD

**Issue by jsejcksn** [denoland/vscode_deno#394]
### test

**Describe the bug**
The command palette entry does not seem to work. It only results in the error described below. I'm exploring this feature for the first time.

**To Reproduce**

1. Command palette > activate the command named _Deno: Reload Import Registries Cache_

2. A notification appears:
> Command 'Deno: Reload Import Registries Cache' resulted in an error (Running the contributed command: 'deno.reloadImportRegistries' failed.)

**Expected behavior**

Not sure. It's never succeeded.

**Screenshots**

<img width="449" alt="Screen Shot 2021-04-16 at 00 42 16" src="https://user-images.githubusercontent.com/868251/114977980-33491f80-9e4e-11eb-8bab-403ae8844668.png">

**Versions**

vscode: `code --version`
```
1.55.2
3c4e3df9e89829dce27b7b5c24508306b151f30d
x64
```
deno: `deno --version`
```
deno 1.9.0 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2
```
extension: `code --list-extensions --show-versions | grep deno`
```
denoland.vscode-deno@3.3.0
```

### notes

My `.vscode/settings.json` looks like this:
```json
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": false,
  "deno.suggest.imports.hosts": {
    "https://deno.land/": true
  }
}

```

**Comment by kitsonk** [comment]
There should have been additional information on the `OUTPUT` tab with the `Deno Language Server` selected in the dropdown.

**Comment by jsejcksn** [comment]
> There should have been additional information on the `OUTPUT` tab with the `Deno Language Server` selected in the dropdown.

@kitsonk It didn't. Below is a screen recording of a reproduction. Is there another way to get diagnostics?

![trim](https://user-images.githubusercontent.com/868251/115009629-19b9cf00-9e72-11eb-9100-fe54efb998ac.gif)

**Comment by danopia** [comment]
I'm seeing the same behavior on the same extension version, 3.3.0. I also can't find any output from the action attempt.

**Comment by lucacasonato** [comment]
I can also reproduce.

**Comment by jsejcksn** [comment]
Hi @kitsonk: I noticed that you closed this issue, but I am not seeing any change in behavior, other than that now the error is displayed in a modal instead of a notification. Will you please reopen it?

<img width="265" alt="Screen Shot 2021-06-13 at 12 12 21" src="https://user-images.githubusercontent.com/868251/121816405-0abc8680-cc41-11eb-9478-a09d76239243.png">

Updated env info:

```
% deno --version
deno 1.11.0 (release, x86_64-apple-darwin)
v8 9.1.269.35
typescript 4.3.2

% code --version
1.57.0
b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
x64

% code --list-extensions --show-versions | grep deno
denoland.vscode-deno@3.6.1
```

**Comment by dsherret** [comment]
I was able to reproduce this. Opened https://github.com/denoland/deno/pull/11123 that should fix it.

**Comment by kitsonk** [comment]
Fixed in denoland/deno#11123

**Comment by jsejcksn** [comment]
@kitsonk Should this be working now? The fix PR was advertised in the release notes for `1.11.3`, but I'm still not seeing any change in behavior.

env info:
```
% deno --version
deno 1.11.4 (release, x86_64-apple-darwin)
v8 9.1.269.35
typescript 4.3.2

% code --version
1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64

% code --list-extensions --show-versions | grep deno
denoland.vscode-deno@3.6.1
```

**Comment by dsherret** [comment]
Just looked into this and another bug related to this was that capturing of `client` in the creation of the import registries command:

https://github.com/denoland/vscode_deno/commit/6bf04545b39903ab6ed1eab599b10f5f5c56887f#diff-1cd105d0893b8fff673276402088a4c08a09648ca92c8516f88670f786dc15c8R91-R95

We'll need to do a plugin release too.

**Comment by jsejcksn** [comment]
@dsherret Thanks. Will you please reopen until the fixes are merged?

**Comment by kitsonk** [comment]
They are merge, just not released.  We close issues when merged.

**Comment by jsejcksn** [comment]
Just tested in release v`3.7.0`: There is no UI feedback when running the command, and `deno.land` import URLs seem to autocomplete as expected.
