### ISSUE TITLE
Formatter ignores deno.json

### ISSUE THREAD

**Issue by ralfstx** [denoland/vscode_deno#933]
I have a project with a top-level `deno.json` that includes a `fmt` config with `"singleQuote": true`.
Calling `deno fmt` in the terminal respects this setting. However, the auto-formatter keeps re-formatting with double quotes.
I have tried to include `"deno.config": "./deno.json"` in the VSCode settings, but to no avail.

**Reproduction**

`.vscode/settings.json`:
```json
{
  "deno.enable": true,
  "editor.defaultFormatter": "denoland.vscode-deno",
  "editor.formatOnSave": true
}
```

`deno.json`:
```json
{
  "fmt": {
    "lineWidth": 100,
    "singleQuote": true,
    "include": [
      "src/"
    ]
  }
}
```

**Expectation**

I would expect that the Deno extension respects the configuration in `deno.json`.

**Versions**

vscode: 1.82.2, deno: 1.35.0, extension: v3.23.1

**Comment by bartlomieju** [comment]
Do you get the same problem after updating to Deno v1.37? I believe this problem was fixed in the recent version of Deno.

**Comment by ralfstx** [comment]
I updated to Deno 1.37.0, restarted everything, but the problem persists.

**Comment by bartlomieju** [comment]
Cc @nayeemrmn

**Comment by nayeemrmn** [comment]
@ralfstx Check your **user** `settings.json` to see if there's anything like:
```js
{
    "[typescript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    }
}
```
and delete it if there is. I just checked mine and it was there, probably added automatically by something. This will override top-level `editor.defaultFormatter` even if it's in project settings. Most of our users don't experience this because they set the formatter per-language and that will always override user settings.

**Comment by ralfstx** [comment]
That was it. Removed this user setting and it works now. Thank you so much!

**Comment by bartlomieju** [comment]
Nayeem could we document it in the README in a troubleshooting section?
